insert into `library_db`.books_list (`name`, `author`, `year`, `image_name`, `description`, `number_of_pages`, `clicks`,
                                     `views`)
values ('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', 'Андрей Богуславский', 2003, '22.jpg',
        'Лекции и практикум по программированию на Си++', 351, 0, 0),
       ('Програмирование на языке Go', 'Марк Саммерфильд', 2008, '23.jpg', 'Теория и практикум на Go', 232, 0, 0),
       ('Толковый словарь сетевых терминов и аббревиатур', 'М. Вильямс', 2006, '25.jpg',
        'Толковый словарь сетевых терминов и аббревиатур', 220, 0, 0),
       ('Python for Data Analysis', 'Уэс Маккинни', 1982, '26.jpg', 'Python for Data Analysis', 220, 0, 0),
       ('Thinking in Java (4th Edition)', 'Брюс Эккель', 1990, '27.jpg', 'Thinking in Java (4th Edition)', 215, 0, 0),
       ('Introduction to Algorithms', 'Томас Кормен, Чарльз Лейзерсон, Рональд Ривест, Клиффорд Штайн', 2020,
        '29.jpg', 'Introduction to Algorithms', 130, 0, 0),
       ('JavaScript Pocket Reference', 'Дэвид Флэнаган', 1995, '31.jpg', 'JavaScript Pocket Reference', 260, 0, 0),
       ('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles', 'Гэри Маклин Холл',
        2020, '32.jpg', 'Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles', 320, 0, 0),
       ('SQL: The Complete Reference', 'Джеймс Р. Грофф', 2010, '33.jpg', 'SQL: The Complete Reference', 280, 0, 0),
       ('PHP and MySQL Web Development', 'Люк Веллинг', 2002, '34.jpg', 'PHP and MySQL Web Development', 450, 0, 0),
       ('Статистический анализ и визуализация данных с помощью R', 'Сергей Мастицкий', 2003,
        '35.jpg', 'Статистический анализ и визуализация данных с помощью R', 145, 0, 0),
       ('Computer Coding for Kid', 'Джон Вудкок', 2006, '36.jpg', 'Computer Coding for Kid', 220, 0, 0),
       ('Exploring Arduino: Tools and Techniques for Engineering Wizardry', 'Джереми Блум', 2000,
        '37.jpg', 'Exploring Arduino: Tools and Techniques for Engineering Wizardry', 420, 0, 0),
       ('Программирование микроконтроллеров для начинающих и не только', 'А. Белов', 2007,
        '38.jpg', 'Программирование микроконтроллеров для начинающих и не только', 180, 0, 0),
       ('The Internet of Things', 'Сэмюэл Грингард', 1999, '39.jpg', 'The Internet of Things', 215, 0, 0),
       ('Sketching User Experiences: The Workbook', 'Сет Гринберг', 1995, '40.jpg',
        'Sketching User Experiences: The Workbook', 310, 0, 0),
       ('InDesign CS6', 'Александр Сераков', 2011, '41.jpg', 'InDesign CS6', 230, 0, 0),
       ('Адаптивный дизайн. Делаем сайты для любых устройств', 'Тим Кедлек', 2001, '42.jpg',
        'Адаптивный дизайн. Делаем сайты для любых устройств', 330, 0, 0),
       ('Android для разработчиков', 'Пол Дейтел, Харви Дейтел', 2001, '43.jpg', 'Android для разработчиков', 150, 0, 0),
       ('Clean Code: A Handbook of Agile Software Craftsmanship', 'Роберт Мартин', 2003,
        '44.jpg', 'Clean Code: A Handbook of Agile Software Craftsmanship', 420, 0, 0),
       ('ESwift Pocket Reference: Programming for iOS and OS X', 'Энтони Грей', 2004, '45.jpg',
        'ESwift Pocket Reference: Programming for iOS and OS X', 350, 0, 0),
       ('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence',
        'Мартин Фаулер, Прамодкумар Дж. Садаладж', 2000, '46.jpg',
        'NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence', 510, 0, 0),
       ('Head First Ruby', 'Джей Макгаврен', 2000, '47.jpg', 'Head First Ruby', 270, 0, 0),
       ('Practical Vim', 'Дрю Нейл', 2000, '48.jpg', 'Practical Vim', 370, 0, 0);